### ISSUE TITLE
Add option to customize favicon

### ISSUE THREAD

**Issue by dantehemerson** [matthieuauger/gatsby-theme-meetup#10]
At the moment the favicon is called `jamstack-square.png`:

https://github.com/matthieuauger/gatsby-theme-meetup/blob/ec9e5bb9359e7330aeec5fc3607391e3fef7e5a0/packages/%40matthieuauger/gatsby-theme-meetup/gatsby-config.js#L59-L62

I think you should add the option to customize the route for the favicon and by default it should be called `favicon.png`

**Comment by dantehemerson** [comment]
@matthieuauger  I would like to work on this if you want.

**Comment by matthieuauger** [comment]
@dantehemerson Many thanks for declaring this issue. If you want to work on this one, I'd be happy to review and merge it 👍

**Comment by matthieuauger** [comment]
Fixed by @MaisaMilena :)
